import Head from "next/head";
import { BsFillMoonStarsFill, BsFillDiamondFill } from "react-icons/bs";
import Image from "next/image";
import { AiFillLinkedin } from "react-icons/ai";
import { IoLogoFirebase } from "react-icons/io5";
import { TbSquareToggle } from "react-icons/tb";
import { DiHeroku } from "react-icons/di";
import cat from "../public/cat.png";
import codeimg from "../public/codeimg.png";
import web2 from "../public/web2.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Lamas Jonathan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">czx</h1>
            <ul className="flex items-center">
              <li>
                {" "}
                <BsFillMoonStarsFill
                  onClick={() => {
                    setDarkMode(!darkMode);
                  }}
                  className="cursor-pointer"
                />
              </li>
              <li>
                {" "}
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Lamas Ibirez Jonathan
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-500 md:text-xl max-w-xl mx-auto dark:text-gray-300">
              {" "}
              lorem insup
            </p>
          </div>

          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-800 dark:text-white">
            <AiFillLinkedin />
          </div>
          <div className="relative mx-auto bg-gradient-to-b  from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-96 md:h-96">
            <Image src={cat} layout="fill" objectFit="cover" />
          </div>
        </section>
        {/* second part */}

        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white"> Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-500 dark:text-gray-300">
              lorem insup
            </p>
            <p className="text-md py-2 leading-8 text-gray-500 dark:text-gray-300">
              {" "}
              <span className="text-teal-500">lorem insup</span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-500 dark:text-gray-300">
              lorem insup
            </p>
            {/* ya veras vos que invetar loco yo codeo nomas */}
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <div className="flex justify-center">
                <Image src={codeimg} width={100} height={100} />
              </div>
              <h3 className="text-xl font-medium pt-8 pb-2 dark:text-white">
                Technologies
              </h3>
              <div className="flex-wrap">
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  JavaScript-ReactJs-NodeJs
                </p>
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  TailwindCss-Bootstrap
                </p>
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  MySql-PostgreSql-MongoDB
                </p>
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  Git-Insomnia Rest-Figma
                </p>
              </div>
            </div>
            {/* s */}
            <div className="text-center shadow-lg p-12 rounded-xl my-10 dark:bg-gray-800">
              <div className="flex justify-center">
                <Image src={codeimg} width={100} height={100} />
              </div>
              <h3 className="text-xl font-medium pt-8 pb-2 dark:text-white">
                Languages
              </h3>
              <div className="flex-wrap">
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  Spanish: Natal
                </p>
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  English: Upper-Intermediate
                </p>
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  French: Basic
                </p>
                <p className="text-gray-500 py-1 dark:text-gray-300">
                  Italian: Basic
                </p>
              </div>
            </div>
            {/* s */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800">
              <div className="flex justify-center">
                <Image src={codeimg} width={100} height={100} />
              </div>
              <h3 className="text-xl font-medium pt-8 pb-2 ml-1 dark:text-white">
                Services Cloud Hosting
              </h3>
              <div className="flex-wrap ">
                <div className=" flex justify-center mt-1">
                  <ul className="text-gray-500 flex items-center  dark:text-gray-300">
                    <IoLogoFirebase />

                    <li className="ml-1">Firebase</li>
                  </ul>
                </div>
                <div className=" flex justify-center mt-1">
                  <ul className="text-gray-500 flex items-center  dark:text-gray-300">
                    <TbSquareToggle />

                    <li className="ml-1">Render</li>
                  </ul>
                </div>
                <div className=" flex justify-center mt-1">
                  <ul className="text-gray-500 flex items-center  dark:text-gray-300">
                    <li>
                      <BsFillDiamondFill />
                    </li>
                    <li className="ml-1">Netlify</li>
                  </ul>
                </div>
                <div className=" flex justify-center mt-1">
                  <ul className="text-gray-500 flex items-center  dark:text-gray-300">
                    <li>
                      <DiHeroku />
                    </li>
                    <li className="ml-1">Heroku</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* 3rd part */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-500 dark:text-gray-300">
              lorem insup
            </p>
            <p className="text-md py-2 leading-8 text-gray-500 dark:text-gray-300">
              {" "}
              <span className="text-teal-500">lorem insup</span>
            </p>
            <p className="text-md py-2 leading-8 text-gray-500 dark:text-gray-300">
              lorem insup
            </p>
            {/* ya veras vos que invetar loco yo codeo nomas */}
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-grap">
            {/* webimage1 */}
            <div className="basis-1/2 flex-1">
              <Image
                src={codeimg}
                className="cursor-pointer rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            {/* webimage2 */}
            <div className="basis-1/2 flex-1">
              <a
                href="https://mern-mtk-jonathan-lamas.onrender.com/"
                className="flex h-100 w-100"
              >
                <Image
                  src={web2}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />{" "}
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
